spring:
  application:
    name: user-service
  zipkin:
    base-url: http://localhost:8090
  boot:
    admin:
      url:
        http://localhost:8070
eureka:
  client:
    serviceUrl:
      defaultZone: http://eurekaserver:8761/eureka/
  instance:
    preferIpAddress: true

    
logging:
  level:
    org:
      springframework:
        cloud:
          sleuth: DEBUG  
infoprofile: node0  
---


server:
    port: 9010
spring:
    profiles: node1
infoprofile: node1
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
---

spring:
    profiles: node2
server:
    port: 9011
infoprofile: node2    
---

spring:
    profiles: node3
infoprofile: node3
server:
    port: 9012