version: '2'
services:
  eurekaserver:
    image: sanitas-eurekaserver
    container_name: container_eureka
    command: java -jar eurekaserver.jar
    ports:
      - "8761:8761"
  zuul:
    image: sanitas-zuul
    container_name: container_zuul
    command: java -jar zuul.jar
    ports:
      - "80:8081"
  user:
    image: sanitas-user
    command: java -jar user.jar
    ports:
      - "9010"
    links:
      - eurekaserver
      - zuul
