spring:
  application:
    name: admin-server
server:
  port: 8070
eureka:
  client:
    eureka-server-u-r-l-context: http://localhost:8761
spring.boot.admin.routes.endpoints: env,metrics,trace,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,hystrix.stream, activiti
spring.boot.admin.turbine:
  clusters: default
  url: http://localhost:8989/turbine.stream