spring:
  application:
    name: Eureka Server
server:
  port: 8761
eureka:
  instance:
    hostname: eurekaserver
  server:
    wait-time-in-ms-when-sync-empty: 0
    enable-self-preservation: true
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname:localhost}:${server.port}/eureka/
      