spring:
  application:
    name: score-service
#  zipkin:
#    base-url: http://localhost:8090
  boot:
    admin:
      url:
        http://localhost:8070
      
eureka:
  client:
    serviceUrl:
      defaultZone: http://eurekaserver:8761/eureka/
  instance:
    preferIpAddress: true

logging:
  level:
    org:
      springframework:
        cloud:
          sleuth: INFO
server:
    port: 9000
infoprofile: node1 

---


server:
    port: 9000
spring:
    profiles: node1
infoprofile: node1  
    
---

spring:
    profiles: node2
server:
    port: 9001
infoprofile: node2
