spring:
  application:
    name: zipkin-server
  sleuth:
    enabled: false
server:
  port: 8090
logging:
  level.org.springframework.cloud: DEBUG
eureka:
  client:
    eureka-server-u-r-l-context: http://localhost:8761
